### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by gmile** [Nebo15/mithril.api#59]
Docs:
- [x] Repository has meaningful README.md that describes what service does.
- [ ] Service API matches Apiary description.
- [x] If applicable - there are link to Docker Hub.
- [x] (if repo is public) Docker Hub page links to `/docs/ENVIRONMENT.md` file and repo.
- [x] `README.md` contains list of third-party dependencies: eg. PostgreSQL or some NIF lib.

Configuration:
- [x] All reasonable configuration data is taken from environment variables.
- [x] `.env` file is up to date (looks [ok](https://github.com/Nebo15/mithril.api/blob/master/.env)).
- [x] `/docs/ENVIRONMENT.md` file is present and describes configuration options ([exists](https://github.com/Nebo15/mithril.api/blob/master/docs/ENVIRONMENT.md)).
- [x] `LOG_LEVEL` env [is used](https://github.com/Nebo15/ael.api/blob/master/lib/ael_api/application.ex#L14).
- [x] `ERLANG_COOKIE` is [accepted at start-time](https://github.com/Nebo15/annon.api/blob/master/rel/templates/vm.args.eex#L5) (done in https://github.com/Nebo15/mithril.api/commit/b2a0f52).

Logging:
- [x] Logs are written in JSON format (`logger_json`) ([done](https://github.com/Nebo15/mithril.api/blob/c4ee6c3aaafbc997903a8b53e7eea03136958f4d/mix.exs#L60)).
- [x] Logs does not contain critical data even in DEBUG mode: full dumps of objects that contain it, secrets, tokens, etc. If so - drop log or hide secret from it via Logger configuration (and make sure it's applied) (looks like [done](https://github.com/Nebo15/mithril.api/search?utf8=%E2%9C%93&q=Logger&type=)).

Security:
- [x] There are no secrets to any service in repository source code. (If not - delete them and tell me to rotate them.)
- [x] There are no secrets that is packed to a container in a CI process. (If not - delete them and tell me to rotate them.)

Debugging in production:
- [x] `:runtime_tools` in included in application dependencies ([done](https://github.com/Nebo15/mithril.api/blob/c4ee6c3aaafbc997903a8b53e7eea03136958f4d/mix.exs#L27)).

**Comment by gmile** [comment]
I am closing this in favor of https://github.com/Nebo15/mithril.api/issues/69.
