### ISSUE TITLE
Open-Source Checklist

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/mithril.api#80]
# Compiance
* [ ]  [NIST SP 800-63-3](https://www.nist.gov/itl/tig/special-publication-800-63-3).
* [ ]  [The OAuth 2.0 Authorization Framework](https://tools.ietf.org/html/rfc6749)
* [ ]  [OAuth 2.0 Threat Model and Security Considerations](https://tools.ietf.org/html/rfc6819)
* [ ]  [OAuth 2.0 Token Revocation](https://tools.ietf.org/html/rfc7009)
* [ ]  [OAuth 2.0 Token Introspection](https://tools.ietf.org/html/rfc7662)
* [ ]  [OAuth 2.0 Dynamic Client Registration Protocol](https://tools.ietf.org/html/rfc7591)
* [ ]  [OAuth 2.0 Dynamic Client Registration Management Protocol](https://tools.ietf.org/html/rfc7592)
* [ ]  [OAuth 2.0 for Native Apps](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-10)
* [ ]  [OpenID Connect Core 1.0](http://openid.net/specs/openid-connect-core-1_0.html)
* [ ]  [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html)

# Deployment
* [ ]   Kubernetes Chart
* [ ]   SHA1 deps checks in containers

# Features
* [ ] Sign-Up via social profiles (FB, Twitter)
* [ ] 2FA/TOTP auth

# Security
* [ ] Introspect other tools security and re-apply [1](https://ory.gitbooks.io/hydra/content/security.html)..
